### ISSUE TITLE
Does the SDK support ParseFile yet?

### ISSUE THREAD

**Issue by thphuc** [phillwiggins/flutter_parse_sdk#36]
ParseFile is an important object of Parse platform. Do we support it yet?

**Comment by phillwiggins** [comment]
Hey Tran

We have created ParseFile as a base object but it doesn't upload and download yet. Shouldn't take long to implement. That will be in a near release.

Thanks

**Comment by thphuc** [comment]
That's great! @phillwiggins

**Comment by phillwiggins** [comment]
I'll update this thread when I manage to get that working!

**Comment by phillwiggins** [comment]
Added support. Really needs some testing though. Our current server doesn't have File Storage support. Please can you confirm?

**Comment by ScanEat** [comment]
I tested but there is en error :

```
E/flutter (29953): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (29953): NoSuchMethodError: The getter 'path' was called on null.
E/flutter (29953): Receiver: null
E/flutter (29953): Tried calling: path
E/flutter (29953): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (29953): #1      new ParseFile (file:///Users/toto/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_file.dart:31:42)
E/flutter (29953): #2      parseDecode (file:///Users/toto/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/utils/parse_decoder.dart:67:18)
E/flutter (29953): #3      ParseBase.fromJson.<anonymous closure> (file:///Users/toto/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_base.dart:74:32)
E/flutter (29953): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
E/flutter (29953): #5      ParseBase.fromJson (file:///Users/toto/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_base.dart:64:16)
E/flutter (29953): #6      DietPlan.clone (package:flutter_plugin_example/diet_plan.dart:13:49)
E/flutter (29953): #7      ParseResponse._handleSingleResult (file:///Users/toto/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_response.dart:98:49)
E/flutter (29953): #8      ParseResponse._handleMultipleResults (file:///Users/toto/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_response.dart:89:23)
E/flutter (29953): #9      ParseResponse._handleSuccess (file:///Users/toto/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_response.dart:76:25)
E/flutter (29953): #10     ParseResponse.handleResponse (file:///Users/toto/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_response.dart:31:16)
E/flutter (29953): #11     ParseObject.handleResponse (file:///Users/toto/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_object.dart:218:49)
E/flutter (29953): #12     ParseObject.query (file:///Users/toto/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_object.dart:183:14)
E/flutter (29953): <asynchronous suspension>
E/flutter (29953): #13     QueryBuilder.query (file:///Users/toto/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/network/parse_query.dart:168:19)
E/flutter (29953): <asynchronous suspension>
E/flutter (29953): #14     _MyAppState.query (package:flutter_plugin_example/main.dart:130:39)
E/flutter (29953): <asynchronous suspension>
```

**Comment by rodrigosmarques** [comment]
@thphuc, @ScanEat 

ParseFile It's working. You can test with last release.

**Comment by rodrigosmarques** [comment]
@phillwiggins 
this issue can be closed.

Resolved in the last release.

**Comment by rodrigosmarques** [comment]
@phillwiggins
Close this issue to keep open only what is in trouble.
Resolved in previous releases. It is inactive because it has not received any new comments.
